name: 'Test TypeScript'

on:
  workflow_dispatch:

  schedule:
    - cron: '30 4 4,20 * *'
  
  push:
    paths:
      - '**/test-ts.yml'
      - '**.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './typescript'

    steps:
      - name: 'github / checkout'
        uses: actions/checkout@v4

      - name: 'github / node / setup'
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: './typescript/package-lock.json'
      
      - name: 'node / npm install'
        run: npm install

      - name: 'node / vitest'
        run: npm run test
