name: 'Test Haskell'

on:
  workflow_dispatch:

  schedule:
    - cron: '30 4 * * 2,6'
  
  push:
    paths:
      - 'test-hs.yml'
      - '**.hs'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Git - checkout'
        uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.8.2
        with:
          ghc-version: 9.6.7
          cabal-version: 3.12.1.0

      - name: 'cabal - test'
        run: |
          cd haskell
          cabal test
